### ISSUE TITLE
Authorization after sealer reset

### ISSUE THREAD

**Issue by guenoledc** [ethereum-pocr/kerleano#18]
In GitLab by @phnod1 on May 2, 2022, 14:16

Hello,

Following the reset, can you authorize the sealers?

Thank you

**Comment by guenoledc** [comment]
@khaounen @wiktorhejchman seems the network is stuck

seems this node is not running `0x63c08d9aCd74Dac8B80b9b49E4B7AD5936031ff7`

**Comment by wiktorhejchman** [comment]
@khaounen @guenoledc 

Yes, I was testing a few more things and tried to redeploy the VMs and tried again now, access to GitLab seems to be off already, so cannot get geth or genesis file from gitlab page, not sure where is it all in github now and what are the changes to the code needed. the kerleano doc still seems to be directing towards github, which cannot be accessed anymore. So as of now, SEB nodes are offline.

**Comment by guenoledc** [comment]
> Yes, I was testing a few more things and tried to redeploy the VMs and tried again now, access to GitLab seems to be off already, so cannot get geth or genesis file from gitlab page, not sure where is it all in github now and what are the changes to the code needed. the kerleano doc still seems to be directing towards github, which cannot be accessed anymore. So as of now, SEB nodes are offline.

Sure, that's a problem. @wiktorhejchman I have reactivated your gitlab account until @khaounen can migrate the build

**Comment by khaounen** [comment]
@guenoledc @wiktorhejchman genesis already moved and released [here](https://github.com/ethereum-pocr/ethereum-pocr.github.io/releases)  and the geth already built by CICD too and can be found [here](https://github.com/ethereum-pocr/go-ethereum/releases) i'll be working on the references in the readme tomorrow and will keep you updated

**Comment by guenoledc** [comment]
MR #23 merged
I think we can close this issue
