### ISSUE TITLE
genesis kerleano.json updated from v1.0 to v1.1

### ISSUE THREAD

**Issue by khaounen** [ethereum-pocr/kerleano#24]
@peache41 @wiktorhejchman @guenoledc please reset your network with kerleano v1.1 and create issue to join the network again

```code
export kerleano_version=v1.1 && \
    curl -f -L -o ~/kerleano.json \
    https://github.com/ethereum-pocr/ethereum-pocr.github.io/releases/download/$kerleano_version/kerleano.json
```

**Comment by guenoledc** [comment]
Done here both for sealer and client.

All synchronizing 

My sealer #25
