### ISSUE TITLE
Restart the kerleano network with new consensus model?

### ISSUE THREAD

**Issue by guenoledc** [ethereum-pocr/kerleano#34]
@wiktorhejchman @HallmeSEB @rghoshfinaxys @sjehan @salehmaj 

We have now a new version of the consensus that looks better and that resolve a number of points (thanks to @sjehan )

The `geth` code has changed, the `governance` smart contract also and the `monitoring` tool slightly also.

I would like to organize a complete restart of the kerleano network and properly simulate the initialization process and get ready for testing with APL/SGS also.

Please share your opinion on the matter (worth or not, timing, approach ...) before  we execute

**Comment by rghoshfinaxys** [comment]
This is a fabulous opportunity to align all our sealers on the latest geth image :)

Given we'll be synchronizing, could we leverage this action to include initialization of the production network?

**Comment by wiktorhejchman** [comment]
I think this is a very good idea, both to restart kerleano and sync but also we could maybe initialize the prod network, as I understand it was supposed to happen sometime before the issuance?

We would need to have a bit of time to prepare for a production rollout of all our stuff, it's a copy of acc environment, but there are things to secure like dns, load-balancing etc.

Not sure when do you think we could go ahead with that is it before Christmas or after New Year?

**Comment by guenoledc** [comment]
I feel that we could start some actions for preparing the production ahead of christmas but the actual start will need to be when we have finalized the APL/SGS work

For the kerleano restart I was hoping to get this done after the intrinsec audit and the reherasal is completed

**Comment by guenoledc** [comment]
@rghoshfinaxys @wiktorhejchman 

How do you want to proceed?

Can we schedule things?

**Comment by rghoshfinaxys** [comment]
I'd like to have free rein during the update process, so ideally I'd see something like

- announce to test users that the network will be unavailable at a scheduled time
- CACIB and SEB prepare the update ahead of time, with fallback in case of problems
- Update the network
- basic multi-party test

I can free up a half day for it: if all goes well it shouldn't take more than 30 minutes but it'd be nice to have time in case it doesn't.

I'm available next week, Thursday or Friday. Does this work for you, @guenoledc  @wiktorhejchman  ?

**Comment by guenoledc** [comment]
@rghoshfinaxys 

I think we need to prepare a bit more ahead of this restart and have a meeting between us to agree on the process. 

Maybe we can start documenting what would be required here

I can think of
- having a redefined genesis file uploaded with a release tag so we are sure to all download the right one 
- having the latest binary released with a tag also
- we have 5 machines sealers. I can use mine to init the network and invite you in it. We will reuse the same wallets
- when restarted all our deployment need to be cleaned (because their synchro is at 3.8m block). We have no clear procedure to do this !

Anything else?

**Comment by wiktorhejchman** [comment]
@rghoshfinaxys @guenoledc 

I still need to setup few things, fix database backup, preferrably also monitoring, update the code to finaxys latest version with any possible SEB changes considerations, it might take me a bit and I cannot really spend any time this week on it, next week will also be difficult but I can try. Initially, based on the fact that there are still things to do on our side to prepare for that I think I cannot commit to earlier than 8-9.12 at best probably to actually secure half a day for secure and stable relaunch with availability for fixes.

You guys are the experts so please feel free to educate me exactly what we need to have prepared beforehand etc.

**Comment by guenoledc** [comment]
@wiktorhejchman @rghoshfinaxys 
Hello, as discussed in today's syndicate call, we have agreed to try to reset the kerleano network on the 13/12/2022.

I will look into what is necessary in the coming days and document the procedure here. Stay tuned pls

**Comment by guenoledc** [comment]
## The elements to collect for the genesis / governance smart contracts
- The wallet address of Guenole's node
- The wallet address of SGS as first auditor
- The amount of ₡ to credit to SGS 
- The `BlockDelayBeforeVote` governance constant
- The `BlockSpanForVote`  governance constant
- The `MaxNbBlockPerPeriod`   governance constant
- The `minPledge` defined in `AuditorGovernance.sol` (to be converted to a global constant)
- The number of seconds per block: 4
- The epoch size: 30000
- The activation of certain EIP (1559 : burnable fees, 155 : replay attack, in particular)
- The chainId: 1804
- The genesis timestamp: `0x86e1970`
- The blocks gas limit
- 


## Create the genesis file
When all parameters are set in the `pocr-network/genesis/kerleano.json`, commit and create a release with tag.

When Creating a `v*` tag the `.github/workflows/build-and-release-kerleano.yml` github workflow will be triggered creating a public realease. The tag will be used to download the file from each node

## Building the `geth` module and related release

in the `https://github.com/ethereum-pocr/go-ethereum` repo, merge to main (this push the `geth` to the latest release) and create a release with a tag `v*` to rebuild and create a `geth` stored in the assets of that release

**Comment by guenoledc** [comment]
## Resetting the client nodes

For each of our client nodes, we need to drop the data, download the new binary and genesis file. Then reinitialize the geth db and start the process pointing to the other sealers



## Resetting the kubernetes applications (essentially the databases)

A simple way to do this is to configure in kubernetes a different name for all the databases so it restart from scratch. 

But attention, do not drop the CUSTODY DB tables `custody.tokens` and `custody.wallets` that contains only the management of private keys that have nothing to do with the DLT directly

**Comment by guenoledc** [comment]
## Evaluating the amount of ₡ needed for the first auditor

- 5000₡ min pledge per audit
- Assume 28,000 gas per pledge @ 1GWei per gas
- Assume 1M Gas per audit

**Comment by guenoledc** [comment]
Given that SGS will not be able to provide on time a wallet, we are going to create a HD Wallet and provide it to them.

This wallet is to be used from Metamask for the auditor activities.
