### ISSUE TITLE
Faucet: please credit my wallet

### ISSUE THREAD

**Issue by slyfox90** [ethereum-pocr/kerleano#39]
*Fill this form to claim 1 CRC to be credited to your wallet*

### Required information
* Your wallet address: 0x1E3db8B04144832dE4D41B7c51fd8471cA26c7ed    

### Motivations

*Prepare the setup to fully benefit from Guénolé's IMA workshop next week!*

**Comment by guenoledc** [comment]
@slyfox90 , done and welcome on Kerleano

**Comment by slyfox90** [comment]
TY @guenoledc :)
