### ISSUE TITLE
New sealer request: 0xe9750d0811d7Df073493145bf315D73924399c65

### ISSUE THREAD

**Issue by applied-ai-collective** [ethereum-pocr/kerleano#41]
Hello @guenoledc ! 
My name is Andrei C. and I work for Exaion, I've sent you an email following the exchanges with Simon :)
Please allow my sealer **0xe9750d0811d7Df073493145bf315D73924399c65** to join the network.
Thanks !

**Comment by guenoledc** [comment]
@applied-ai-collective 

Nice to see your request on the testnet

It is ok for CACIB

@wiktorhejchman @johanhormark for SEB please review and confirm that you are ok for including Exaion in the testnet as sealer

@johnny78500 can you please perform the accept procedure on CACIB nodes. I will do it on my node

**Comment by guenoledc** [comment]
Vote done for my node

```js
> clique.getSnapshot()
{
  hash: "0x79c9fe710bef53fae50de704a00fca90db07eec695daaea1ae374cfcb1f806ca",
  number: 4490131,
  recents: {
    4490129: "0xec3f218d9876bfc01e9a4601575fe60f1b2c8f76",
    4490130: "0x1311aef86d1db33db945fc488eeff1c6105b9593",
    4490131: "0x20c8f6d7e11c42c83c9af2f6144c963315106fc9"
  },
  signers: {
    0x1311aef86d1db33db945fc488eeff1c6105b9593: {},
    0x20c8f6d7e11c42c83c9af2f6144c963315106fc9: {},
    0xc16c63da5f6e464148ffc0bcef9e761a16af6004: {},
    0xcca833ec5bb4fceb5145fa2fd65c94c446028ff6: {},
    0xec3f218d9876bfc01e9a4601575fe60f1b2c8f76: {}
  },
  tally: {
    0xe9750d0811d7df073493145bf315d73924399c65: {
      authorize: true,
      votes: 1
    }
  },
  votes: [{
      address: "0xe9750d0811d7df073493145bf315d73924399c65",
      authorize: true,
      block: 4490130,
      signer: "0x1311aef86d1db33db945fc488eeff1c6105b9593"
  }]
}
```

**Comment by johanhormark** [comment]
Hi,
Ok from SEB as well for Exaion to join testnet. @wiktorhejchman<https://github.com/wiktorhejchman> – will you do the practical stuff?
BR
Johan


Johan Hörmark
Investment Banking Equities
SEB Large Corporates & Financial Institutions
Mobile: +46 70 739 23 32
Switchboard: +46 771 621 000
Postal Address: SE-106 40 Stockholm
Office Address: Kungsträdgårdsgatan 8
E-mail: ***@***.******@***.***>
www.seb.se<http://www.seb.se/>
Invoice address: Skandinaviska Enskilda Banken AB, Accounts Payable, SE-106 40 Stockholm
P Please consider the environment before printing this e-mail
CONFIDENTIALITY NOTICE
This e-mail is confidential and may contain legally privileged information. If you have received it by mistake, please inform us by reply e-mail and then delete it (including any attachments) from your system; you should not copy it or in any other way disclose its content to anyone. E-mail is susceptible to data corruption, interception, unauthorized amendment, tampering and virus. We do not accept liability for any such actions or the consequences thereof.

**Comment by johnny78500** [comment]
@applied-ai-collective 

Quorum has been reached and your node should now be a sealer node within the consensus as you can see from the logs : 

```
> clique.getSnapshot()
{
  hash: "0xcd8dc490350168aaabdcb1465106dcd25cacc11897a927525eb4c62577b3a341",
  number: 4595316,
  recents: {
    4595313: "0xcca833ec5bb4fceb5145fa2fd65c94c446028ff6",
    4595314: "0xe9750d0811d7df073493145bf315d73924399c65",
    4595315: "0xec3f218d9876bfc01e9a4601575fe60f1b2c8f76",
    4595316: "0x1311aef86d1db33db945fc488eeff1c6105b9593"
  },
  signers: {
    0x1311aef86d1db33db945fc488eeff1c6105b9593: {},
    0x20c8f6d7e11c42c83c9af2f6144c963315106fc9: {},
    0xc16c63da5f6e464148ffc0bcef9e761a16af6004: {},
    0xcca833ec5bb4fceb5145fa2fd65c94c446028ff6: {},
    0xe9750d0811d7df073493145bf315d73924399c65: {},
    0xec3f218d9876bfc01e9a4601575fe60f1b2c8f76: {}
  },
  tally: {},
  votes: []
}
> clique.getSigners()
["0x1311aef86d1db33db945fc488eeff1c6105b9593", "0x20c8f6d7e11c42c83c9af2f6144c963315106fc9", "0xc16c63da5f6e464148ffc0bcef9e761a16af6004", "0xcca833ec5bb4fceb5145fa2fd65c94c446028ff6", "0xe9750d0811d7df073493145bf315d73924399c65", "0xec3f218d9876bfc01e9a4601575fe60f1b2c8f76"] 
```


Please verify on your side and send us a feedback 👍

**Comment by guenoledc** [comment]
@applied-ai-collective 

As your node is working I have applied a "fake" environmental footprint audit to it so you can start earning CRC.

Look into https://ethereum-pocr.github.io/#/dashboard connecting with your wallet or a delegate wallet to operate as a node operator

Also, please update the name of your node with your company name so we can identify you (currently your node is named geth 1.10.26 go1.19.5 linux). Use the `--miner.extradata="Your node name here"` option in the geth command line

**Comment by applied-ai-collective** [comment]
Hello @guenoledc !
Thanks alot for applying the audit, I can confirm that the node is running !
The `miner.extradata` field has been updated, please let me know if it's OK for you.

I was wondering if you can suggest any monitoring tools or advice to keep an eye on the node. 
For now, I've setup a simple Prometheus configuration.

**Comment by guenoledc** [comment]
@applied-ai-collective can you check your node, it seems to be down.

For the monitoring, we also use prometheus + grafana, so nothing more than what you probably have on all other ethereum like nodes. 

Please check your node and implement an alert when it falls ;-)

**Comment by guenoledc** [comment]
Also, we generally look into the http://ethereum-pocr.github.io/ dashboard to see what nodes are running

**Comment by applied-ai-collective** [comment]
Hello @guenoledc, thanks for noticing and for the info
There were some instabilities yesterday morning, it's been fixed and all is working since. 

I also took the time to test backup and recovery of the node, it's working very well using the Ansible script you provided !

I'll keep monitoring the node and add a Prometheus alert to ensure it says running all the time :)
Thank you !
