### ISSUE TITLE
Faucet: please credit my wallet

### ISSUE THREAD

**Issue by mtoub** [ethereum-pocr/kerleano#42]
*Fill this form to claim 1 CRC to be credited to your wallet*

### Required information
* Your wallet address: 0x444D341Fcd5d8627163b9E27b05Fce11f58A663a        

### Motivations

We would like support the pocrnet in our plateform FeverTokens.

**Comment by guenoledc** [comment]
@mtoub 

Transaction done 

https://ethereum-pocr.github.io/explorer/kerleano/tx/0x57715033a304606fb7306d554df8cb6e1e0a4e4c2a58d19d3fac0a457cc48877

**Comment by mtoub** [comment]
@guenoledc 

Got it, thanks.
