### ISSUE TITLE
Faucet: please credit my wallet

### ISSUE THREAD

**Issue by Magicred-1** [ethereum-pocr/kerleano#43]
*Fill this form to claim 1 CRC to be credited to your wallet*

### Required information
* Your wallet address: 0x8A90ca40372dAEF77532D1C3538E68715Ba36fD7       

### Motivations

Hello ! 

I would like for testing and education purposes, to get some test tokens to create a Green IT dApp in a Hackathon and my future company.

Regards.

**Comment by guenoledc** [comment]
Done and sorry for the looong delay 

https://ethereum-pocr.github.io/explorer/kerleano/tx/0x635619e25913c838b8287f3141845b74faee0d700b78da5f071398c6265b325b
