### ISSUE TITLE
Faucet: please credit my wallet

### ISSUE THREAD

**Issue by ntauth** [ethereum-pocr/kerleano#47]
*Fill this form to claim 1 CRC to be credited to your wallet*

### Required information
* Your wallet address: 0xda0944483deb5766cc6effbd750f139c07e57868

### Motivations

*Explain your reason for requesting CRC*
I need to test that transactions work correctly on the Kerleano testnet

**Comment by guenoledc** [comment]
Done 

https://ethereum-pocr.github.io/explorer/kerleano/tx/0x21b2fefb85e9b34017e9a282935c3eb8cfaf3f7fd9607d868e1bf54f355d15ec
