### ISSUE TITLE
Faucet: please credit my wallet

### ISSUE THREAD

**Issue by Universe-art** [ethereum-pocr/kerleano#48]
### Required information
* Your wallet address: 0x731476dAD33A7E7Dca58Ae4BdDcaddB5c5a34A21      

### Motivations

I will like to conduct some tests with a third party provider

Thank you

**Comment by guenoledc** [comment]
Done

https://ethereum-pocr.github.io/explorer/kerleano/tx/0x9931bbaf6b69af793ed9408ebfbd9a5d503a01a2532bc0ce58ae3932b0c86709

**Comment by Universe-art** [comment]
Thank you
