### ISSUE TITLE
Faucet: please credit my wallet

### ISSUE THREAD

**Issue by Vass1l1** [ethereum-pocr/kerleano#49]
Fill this form to claim 1 CRC to be credited to your wallet

Required information
Your wallet address: 0xda0944483deb5766cc6effbd750f139c07e57868
Motivations
Explain your reason for requesting CRC
I need to test that transactions work correctly on the Kerleano testnet

**Comment by guenoledc** [comment]
I see that you have been able to get some crypto on your wallet.
Please let us know what is needed on your side or close the issue
