### ISSUE TITLE
Faucet: please credit my wallet

### ISSUE THREAD

**Issue by Maxolinho** [ethereum-pocr/kerleano#50]
*Fill this form to claim 1 CRC to be credited to your wallet*

### Required information
* Your wallet address: 0xca8016008CD6F401C19c7d19a4Ab7BD630DeD3B6     

### Motivations

*Explain your reason for requesting CRC*

**Comment by guenoledc** [comment]
Done

https://ethereum-pocr.github.io/explorer/kerleano/tx/0x22c66115b4394a4b50043d335ce309a6e90c21a67f90227d99fada4282bf9c27
