### ISSUE TITLE
Faucet: please credit my wallet 0xca8016008CD6F401C19c7d19a4Ab7BD630DeD3B6

### ISSUE THREAD

**Issue by Maxolinho** [ethereum-pocr/kerleano#51]
*Fill this form to claim 1 CRC to be credited to your wallet*

### Required information
* Your wallet address: 0xca8016008CD6F401C19c7d19a4Ab7BD630DeD3B6     

### Motivations

*Explain your reason for requesting CRC*

**Comment by guenoledc** [comment]
Done
