### ISSUE TITLE
Faucet: please credit my wallet

### ISSUE THREAD

**Issue by Davapot** [ethereum-pocr/kerleano#54]
*Fill this form to claim 1 CRC to be credited to your wallet*

### Required information
* Your wallet address: 0x057dbf9adf567b4b7fed0b54197e913bf8e1c2de

### Motivations

to test the so|cash framework

**Comment by guenoledc** [comment]
Done: https://ethereum-pocr.github.io/explorer/kerleano/tx/0xa6d7ec3f5a228efaa78750f825ae9eb551035c8e0ab512c9945a3732d739e085
