### ISSUE TITLE
Faucet: please credit my wallet

### ISSUE THREAD

**Issue by YBadiss** [ethereum-pocr/kerleano#56]
*Fill this form to claim 1 CRC to be credited to your wallet*

### Required information
* Your wallet address: 0xbBf96D83c2b11A4b5A47e8F961D619015b851392

### Motivations

Hi!

I am working with FeverTokens and Keyring on an integration of SoBond for which I need to interact with contracts deployed on Kerleano.

Thanks in advance =]

**Comment by guenoledc** [comment]
Done 

https://ethereum-pocr.github.io/explorer/kerleano/tx/0x05ca6d4f1f46687ff127bde5a348120991f1f6dba538baae08e7b64c6f53315a
