### ISSUE TITLE
Faucet: please credit my wallet

### ISSUE THREAD

**Issue by NLiccardo** [ethereum-pocr/kerleano#57]
*Fill this form to claim 1 CRC to be credited to your wallet*

### Required information
* Your wallet address: 0x56630bA9b9D7553f328076671A1549622DBeB497        

### Motivations

*Explain your reason for requesting CRC*

**Comment by guenoledc** [comment]
Done 

https://ethereum-pocr.github.io/explorer/kerleano/tx/0x8e270d9669aafb115e31ef38d53213bd1584e7600f71ccc977dc1607b6964f02
