### ISSUE TITLE
Faucet: please credit my wallet

### ISSUE THREAD

**Issue by micklouiset** [ethereum-pocr/kerleano#58]
Hi, I would need 10 CRC please

Address : 0x731476dAD33A7E7Dca58Ae4BdDcaddB5c5a34A21

**Comment by guenoledc** [comment]
Done

https://ethereum-pocr.github.io/explorer/kerleano/tx/0x28dac9725b3bf2bb9e9d49e45f3fe3cb3736696ba370fa749539ebd397c9e11f
