### ISSUE TITLE
Faucet: please credit my wallet

### ISSUE THREAD

**Issue by Ty-HA** [ethereum-pocr/kerleano#59]
*Fill this form to claim 1 CRC to be credited to your wallet*

### Required information
* Your wallet address: 0x07ed6555948c8f1a8c324adfdc1ffcfd300ec4fe

### Motivations

I am testing So Cash, because I will participate to Vierzon hackathon, and I am interesting about CACIB use cases

**Comment by guenoledc** [comment]
@Ty-HA 

The transfer is done

https://ethereum-pocr.github.io/explorer/kerleano/tx/0xe1d4ba4331301f00973c23ee621cb66dd871b3c14af772323bd968743464f9eb
