### ISSUE TITLE
Sealer 0xe9750d0811d7df073493145bf315d73924399c65 is down

### ISSUE THREAD

**Issue by guenoledc** [ethereum-pocr/kerleano#60]
Hello @applied-ai-collective

ref #41 

Your sealer is down on Kerleano. Please check.

Thanks

**Comment by applied-ai-collective** [comment]
Hello @guenoledc, 
The validator is back up on Kerleano, just checked.
Thank you.

**Comment by guenoledc** [comment]
Yes perfect. Thanks
